---------------------------
--QNA_TYPE
---------------------------
INSERT INTO QNA_TYPE VALUES(1,'Community');
INSERT INTO QNA_TYPE VALUES(2,'YeSS Mall');
INSERT INTO QNA_TYPE VALUES(3,'YeSS Market');
INSERT INTO QNA_TYPE VALUES(4,'Etc');
---------------------------
--FAQ
---------------------------
INSERT INTO FAQ
(NO, QNA_TYPE_NO, ADMIN_NO, TITLE, CONTENT)
VALUES(SEQ_FAQ_NO.NEXTVAL, 1, 1, 'Community 이용안내', 
'Community는 YeSS 회원들이 서로 소통이 가능한 공간입니다.<br><br>
나만의 재활용 활용 노하우를 공유하는 정보게시판,
재활용 활용 방법에 대해 질문하는 문의게시판,
자유롭게 이용하는 잡담게시판과 사진게시판이 있습니다.<br><br>
YeSS 회원들과 자유롭게 소통해 보세요!
');

INSERT INTO FAQ
(NO, QNA_TYPE_NO, ADMIN_NO, TITLE, CONTENT)
VALUES(SEQ_FAQ_NO.NEXTVAL, 2, 1, 'YeSS Mall 이용안내', 
'YeSS Mall에서는 환경보호에 동참하고자, 친환경 제품들을 판매하고 있습니다.<br><br>
YeSS에서 활동 후 획득한 포인트는 YeSS Mall에서 사용이 가능합니다.<br><br>
포인트를 사용해서 다양한 제품들을 만나보세요!
');
INSERT INTO FAQ
(NO, QNA_TYPE_NO, ADMIN_NO, TITLE, CONTENT)
VALUES(SEQ_FAQ_NO.NEXTVAL, 2, 1, '교환/환불은 어떻게 하나요?', 
'[마이페이지] - [My Mall] - [주문내역]에서 신청 가능합니다.<br><br>
결제일 기준 30일 이내의 제품에 한하여 교환/환불 신청이 가능합니다.<br><br>
신청일 기준 3일 이내에 교환/환불 처리가 완료됩니다.
');
INSERT INTO FAQ
(NO, QNA_TYPE_NO, ADMIN_NO, TITLE, CONTENT)
VALUES(SEQ_FAQ_NO.NEXTVAL, 3, 1, 'YeSS Market 이용안내', 
'YeSS Market은 회원간 서로 거래가 가능한 공간입니다.<br><br>
검색 또는 게시글 작성을 통해 거래 상대를 찾아보세요.<br><br>
원하시는 거래 게시글을 발견했다면, 비밀댓글 기능으로 연락처를 남겨보세요.<br><br>
<br>
* 1:1 거래는 회원간 거래이므로, YeSS측에서 책임을 지지 않습니다. 신중한 거래 부탁드립니다.
');
INSERT INTO FAQ
(NO, QNA_TYPE_NO, ADMIN_NO, TITLE, CONTENT)
VALUES(SEQ_FAQ_NO.NEXTVAL, 4, 1, 'How To YeSS 이용안내', 
'How To YeSS는 분리배출의 표준화된 방식을 제공하는 공간입니다.<br><br>
How To YeSS는 YeSS에서 등록하고 관리합니다.<br><br>
원하시는 정보가 없거나, 잘못된 정보를 발견한 경우, 1:1 문의를 통해 문의를 남겨주세요.
');
INSERT INTO FAQ
(NO, QNA_TYPE_NO, ADMIN_NO, TITLE, CONTENT)
VALUES(SEQ_FAQ_NO.NEXTVAL, 4, 1, 'Where To YeSS 이용안내', 
'Where To YeSS는 재활용제품을 다양하게 활용할 수 있는 장소를 소개하는 공간입니다.<br><br>
재활용 제품 교환소, 재활용제품을 활용하는 공방 또는 원데이클래스 등의 위치 정보를 제공합니다.<br><br>
원하시는 정보가 없거나, 잘못된 정보를 발견한 경우, 1:1 문의를 통해 문의를 남겨주세요.
');

COMMIT;

---------------------------
--YeSS Market 게시글 (56개)
---------------------------
INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-10-01', 'N', '2022-10-01', '46', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2022-10-21', 'N', '2022-10-21', '12', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-10-27', 'N', '2022-10-27', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2022-11-07', 'N', '2022-11-07', '14', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-11-14', 'N', '2022-11-14', '7', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2022-11-17', 'N', '2022-11-17', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-11-21', 'N', '2022-11-21', '13', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-11-27', 'N', '2022-11-27', '3', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-12-03', 'N', '2022-12-03', '2', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2022-12-15', 'N', '2022-12-15', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-12-17', 'N', '2022-12-17', '46', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2022-12-21', 'N', '2022-12-21', '12', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-12-27', 'N', '2022-12-27', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-01', 'N', '2023-01-01', '14', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2023-01-03', 'N', '2023-01-03', '7', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2023-01-04', 'N', '2023-01-04', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2023-01-04', 'N', '2023-01-04', '13', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2023-01-04', 'N', '2023-01-04', '3', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2023-01-04', 'N', '2023-01-04', '2', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-04', 'N', '2023-01-04', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2023-01-13', 'N', '2023-01-13', '46', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2023-01-13', 'N', '2023-01-13', '12', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2023-01-13', 'N', '2023-01-13', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2023-01-13', 'N', '2023-01-13', '14', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2023-01-13', 'N', '2023-01-13', '7', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2023-01-13', 'N', '2023-01-13', '21', 'N');


--YeSS Market 사진 (56번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '56', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '56', '랜턴.PNG', '랜턴.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '56', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '56', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '56', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (55번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '55', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '55', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '55', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (54번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '54', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '54', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (53번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '53', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '53', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (52번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '52', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (51번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '51', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (50번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '50', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '50', '랜턴.PNG', '랜턴.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '50', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '50', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '50', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (49번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '49', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '49', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '49', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (48번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '48', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '48', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (47번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '47', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '47', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (46번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '46', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '46', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '46', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (45번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '45', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '45', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (44번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '44', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '44', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (43번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '43', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (42번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '42', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (41번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '41', '담요.PNG', '담요.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (40번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '40', '조명.PNG', '조명.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '40', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '40', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (39번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '39', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '39', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '39', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (38번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '38', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '38', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (37번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '37', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '37', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (36번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '36', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '36', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '36', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (35번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '35', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '35', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (34번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '34', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '34', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (33번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '33', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (32번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '32', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (31번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '31', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '31', '랜턴.PNG', '랜턴.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '31', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '31', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '31', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (30번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '30', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (29번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '29', '담요.PNG', '담요.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (28번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '28', '발매트.PNG', '발매트.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (27번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '27', '커튼.PNG', '커튼.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (26번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '26', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '26', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '26', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (25번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '25', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '25', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (24번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '24', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '24', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (23번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '23', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (22번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '22', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (21번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '21', '담요.PNG', '담요.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (20번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '20', '조명.PNG', '조명.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '20', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '20', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (19번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '19', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '19', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '19', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (18번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '18', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '18', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (17번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '17', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '17', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (16번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '16', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '16', '랜턴.PNG', '랜턴.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '16', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '16', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '16', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (15번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '15', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (14번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '14', '담요.PNG', '담요.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (13번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '13', '발매트.PNG', '발매트.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (12번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '12', '커튼.PNG', '커튼.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (11번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '11', '랜턴.PNG', '랜턴.PNG' ,'resources/upload/market', 'Y');

INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '10', '슬리퍼.PNG', '슬리퍼.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '10', '담요.PNG', '담요.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '10', '침대커버.PNG', '침대커버.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (9번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '9', '담요.PNG', '담요.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '9', '침대커버.PNG', '침대커버.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '9', '커튼.PNG', '커튼.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (8번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '8', '침대커버.PNG', '침대커버.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '8', '커튼.PNG', '커튼.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (7번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '7', '커튼.PNG', '커튼.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '7', '발매트.PNG', '발매트.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (6번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '발매트.PNG', '발매트.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '랜턴.PNG', '랜턴.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '조명.PNG', '조명.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '담요.PNG', '담요.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '침대커버.PNG', '침대커버.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (5번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '5', '조명.PNG', '조명.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (4번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '4', '멀티탭.PNG', '멀티탭.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (3번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '3', '벽지.PNG', '벽지.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (2번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '2', '후라이팬.PNG', '후라이팬.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (1번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '1', '랜턴.PNG', '랜턴.PNG' ,'resources/upload/market', 'Y');


--YeSS Market 댓글 (56번글)
INSERT INTO MARKET_CMT
(NO, MEMBER_NO, MARKET_NO, CMT)
VALUES(SEQ_MARKET_CMT_NO.NEXTVAL, 2, 56, '오늘의집에서 찾아보세요!!');
INSERT INTO MARKET_CMT
(NO, MEMBER_NO, MARKET_NO, CMT)
VALUES(SEQ_MARKET_CMT_NO.NEXTVAL, 3, 56, '찾아보고 연락드릴게요~');
INSERT INTO MARKET_CMT
(NO, MEMBER_NO, MARKET_NO, CMT, SECRET_YN)
VALUES(SEQ_MARKET_CMT_NO.NEXTVAL, 3, 56, '010-5333-5991 연락주세요~~', 'Y');

COMMIT;

---------------------------
		INSERT INTO MARKET_CMT
		(
			NO
			, MEMBER_NO
			, MARKET_NO
			, CMT
			, SECRET_YN
		)
		VALUES
		(
			SEQ_MARKET_CMT_NO.NEXTVAL
			, 1
			, SEQ_MARKET_NO.CURRVAL
			, 'ㅎㅎㅎㅎ'
			, 'Y'
		);



COMMIT;

SELECT
    MC.NO
    , MB.NICK
    , MC.MARKET_NO
    , MC.CMT
    , TO_CHAR(MC.MODIFY_DATE, 'yyyy-mm-dd') AS MODIFY_DATE
    , MC.SECRET_YN
FROM MARKET_CMT MC
JOIN MEMBER MB ON MC.MEMBER_NO = MB.NO
WHERE MARKET_NO = 37
AND DELETE_YN = 'N';

SELECT COUNT(*)
FROM MARKET_CMT
WHERE MARKET_NO = 37
AND DELETE_YN = 'N';

SELECT 
		    MK.NO
		    , MB.NICK
		    , MK.TITLE
		    , MT.MARKET_TYPE
		    , TO_CHAR(MK.ENROLL_DATE, 'yyyy-mm-dd') AS ENROLL_DATE
		    , MK.HIT
		    , MK.TRADE_YN
		    , MA.CHANGE_NAME
            , NVL(COUNT(MK.NO)OVER(PARTITION BY MC.MARKET_NO), 0)
FROM MARKET MK
JOIN MEMBER MB ON MK.MEMBER_NO = MB.NO
JOIN MARKET_TYPE MT ON MK.MARKET_TYPE_NO = MT.NO
JOIN MARKET_ATTACHMENT MA ON MK.NO = MA.MARKET_NO
JOIN MARKET_CMT MC ON MK.NO = MC.MARKET_NO
WHERE MK.DELETE_YN = 'N'
AND MA.THUMB_YN = 'Y'
ORDER BY MK.ENROLL_DATE DESC;
        
---------------------------------------------------------------------
---------------------------------------------------------------------
        
SELECT 
    MK.NO
    , MB.NICK
    , MK.TITLE
    , MT.MARKET_TYPE
    , TO_CHAR(MK.ENROLL_DATE, 'yyyy-mm-dd') AS ENROLL_DATE
    , MK.HIT
    , MK.TRADE_YN
    , MA.CHANGE_NAME
    , COUNT(MC.NO) AS CMTCNT
FROM MARKET MK
JOIN MEMBER MB ON MK.MEMBER_NO = MB.NO
JOIN MARKET_TYPE MT ON MK.MARKET_TYPE_NO = MT.NO
JOIN MARKET_ATTACHMENT MA ON MK.NO = MA.MARKET_NO
LEFT OUTER JOIN MARKET_CMT MC ON MK.NO = MC.MARKET_NO 
WHERE MK.DELETE_YN = 'N'
AND MA.THUMB_YN = 'Y'
--AND MARKET_TYPE_NO = '1'
AND TITLE LIKE '%%'
GROUP BY 
    MK.NO
    , MB.NICK
    , MK.TITLE
    , MT.MARKET_TYPE
    , TO_CHAR(MK.ENROLL_DATE, 'yyyy-mm-dd')
    , MK.HIT
    , MK.TRADE_YN
    , MA.CHANGE_NAME
ORDER BY ENROLL_DATE DESC;
        
SELECT
	    MC.NO
	    , MB.NICK
	    , MC.MARKET_NO
	    , MC.CMT
	    , TO_CHAR(MC.MODIFY_DATE, 'yyyy-mm-dd') AS MODIFY_DATE
	    , MC.SECRET_YN
	FROM MARKET_CMT MC
	JOIN MEMBER MB ON MC.MEMBER_NO = MB.NO
	WHERE MARKET_NO = 30
	AND DELETE_YN = 'N'
	ORDER BY no;
        
SELECT COUNT(*)
		FROM MARKET
		WHERE DELETE_YN = 'N'
		AND MEMBER_NO = 2
        ;    

SELECT
			MK.NO
            , MK.TRADE_YN
			, MT.MARKET_TYPE
			, MK.TITLE
			, MK.ENROLL_DATE AS DATE2
			, TO_CHAR(MK.ENROLL_DATE, 'yyyy-mm-dd') AS ENROLL_DATE
			, MK.HIT
		FROM MARKET MK
        JOIN MARKET_TYPE MT ON MK.MARKET_TYPE_NO = MT.NO
        JOIN MEMBER MB ON MK.MEMBER_NO = MB.NO
		WHERE MB.NO = 2
		ORDER BY date2 DESC
        ;
        
        
SELECT
		    MK.NO
		    , MK.TRADE_YN
		    , MT.MARKET_TYPE
		    , MK.TITLE
		    , MC.CMT_DATE AS DATE2
		    , MC.SECRET_YN
		    , MC.CMT
		    , TO_CHAR(MC.CMT_DATE, 'yyyy-mm-dd') AS CMT_DATE
		FROM MARKET MK
		JOIN MARKET_TYPE MT ON MK.MARKET_TYPE_NO = MT.NO
		JOIN MARKET_CMT MC ON MK.NO = MC.MARKET_NO
		JOIN MEMBER MB ON MC.MEMBER_NO = MB.NO
		WHERE MB.NO = 2
		ORDER BY DATE2 DESC
;


SELECT COUNT(*)
		FROM MARKET_CMT
		WHERE DELETE_YN = 'N'
		AND MEMBER_NO = 2
        ;
        
        SELECT COUNT(*)
		FROM MARKET
		WHERE DELETE_YN = 'N'
		AND MEMBER_NO = 2;
        
SELECT
 F.NO
, QT.QNA_TYPE
, F.TITLE
, F.CONTENT
, F.ENROLL_DATE
, TO_CHAR(F.MODIFY_DATE, 'yyyy-mm-dd') AS MODIFY_DATE
, F.MODIFY_DATE AS DATE2
 FROM FAQ F
 JOIN QNA_TYPE QT ON F.QNA_TYPE_NO = QT.NO
 WHERE DELETE_YN = 'N'
 ORDER BY DATE2 DESC
 ;
 
 INSERT INTO QNA
 (
 NO
, MEMBER_NO
, QNA_TYPE_NO
, TITLE
, CONTENT)
VALUES(
SEQ_QNA_NO.NEXTVAL
, 2
, 3
, '제목 질문 날려봄'
, '내용 질문 날려봄');

 
commit;