--더미데이터

---------------------------
--GRADE
---------------------------
INSERT INTO GRADE VALUES(1,'씨앗');
INSERT INTO GRADE VALUES(2,'새싹');
INSERT INTO GRADE VALUES(3,'가지');
INSERT INTO GRADE VALUES(4,'꽃잎');
INSERT INTO GRADE VALUES(5,'옆매');
INSERT INTO GRADE VALUES(8,'비료');
INSERT INTO GRADE VALUES(9,'관리자');
---------------------------
--Member
---------------------------
INSERT INTO MEMBER(NO, ID, PWD, NAME, PHONE, NICK, ADDR)
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', '1234', '관리자', '010-1234-5678', 'admin', '사무실');

INSERT INTO MEMBER(NO, ID, PWD, NAME, PHONE, NICK, ADDR)
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'bk5991', '1234', '김보경', '010-5333-5991', 'ANT', '우리집');

INSERT INTO MEMBER(NO, ID, PWD, NAME, PHONE, NICK, ADDR)
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', '1234', '박서연', '010-8765-4321', 'SY01', '서연이네');

INSERT INTO MEMBER(NO, ID, PWD, NAME, PHONE, NICK, ADDR)
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', '1234', '문동주', '010-4321-8765', 'DJ02', '동주네');

INSERT INTO MEMBER(NO, ID, PWD, NAME, PHONE, NICK, ADDR)
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', '1234', '백재은', '010-5678-1234', 'JE03', '재은이네');

INSERT INTO MEMBER(NO, ID, PWD, NAME, PHONE, NICK, ADDR)
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04', '1234', '우지운', '010-9876-5432', 'JW04', '지운이네');
---------------------------
--YeSS Market 유형 번호
---------------------------
INSERT INTO MARKET_TYPE(NO, MARKET_TYPE) VALUES(SEQ_MARKET_TYPE_NO.NEXTVAL, '팔아요');
INSERT INTO MARKET_TYPE(NO, MARKET_TYPE) VALUES(SEQ_MARKET_TYPE_NO.NEXTVAL, '구해요');
INSERT INTO MARKET_TYPE(NO, MARKET_TYPE) VALUES(SEQ_MARKET_TYPE_NO.NEXTVAL, '나눠요');
INSERT INTO MARKET_TYPE(NO, MARKET_TYPE) VALUES(SEQ_MARKET_TYPE_NO.NEXTVAL, '바꿔요');
---------------------------
--YeSS Market 게시글
---------------------------
INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-10-01', 'N', '2022-10-01', '46', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2022-10-21', 'N', '2022-10-21', '12', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-10-27', 'N', '2022-10-27', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2022-11-07', 'N', '2022-11-07', '14', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-11-14', 'N', '2022-11-14', '7', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2022-11-17', 'N', '2022-11-17', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-11-21', 'N', '2022-11-21', '13', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-11-27', 'N', '2022-11-27', '3', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-12-03', 'N', '2022-12-03', '2', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2022-12-15', 'N', '2022-12-15', '0', 'N');


--YeSS Market 사진 (10번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '10', '멜론.PNG', '멜론.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '10', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '10', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (9번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '9', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '9', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '9', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (8번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '8', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '8', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (7번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '7', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '7', '토마토.PNG', '토마토.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (6번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '토마토.PNG', '토마토.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '포도.PNG', '포도.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '멜론.PNG', '멜론.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (5번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '5', '멜론.PNG', '멜론.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (4번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '4', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (3번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '3', '토마토.PNG', '토마토.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (2번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '2', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (1번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '1', '포도.PNG', '포도.PNG' ,'resources/upload/market', 'Y');

COMMIT;