---------------------------
--YeSS Market 게시글 (20개)
---------------------------
INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-10-01', 'N', '2022-10-01', '46', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2022-10-21', 'N', '2022-10-21', '12', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-10-27', 'N', '2022-10-27', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2022-11-07', 'N', '2022-11-07', '14', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-11-14', 'N', '2022-11-14', '7', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2022-11-17', 'N', '2022-11-17', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-11-21', 'N', '2022-11-21', '13', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-11-27', 'N', '2022-11-27', '3', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-12-03', 'N', '2022-12-03', '2', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2022-12-15', 'N', '2022-12-15', '0', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-10-01', 'N', '2022-10-01', '46', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2022-10-21', 'N', '2022-10-21', '12', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-10-27', 'N', '2022-10-27', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2022-11-07', 'N', '2022-11-07', '14', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-11-14', 'N', '2022-11-14', '7', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '3', '구합니다', '2', '필요한 물건', '필요한 물건 상세정보', '택배거래', '구하는 물건 설명', '2022-11-17', 'N', '2022-11-17', '21', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-11-21', 'N', '2022-11-21', '13', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '2', '팔아요팔아요팔아요', '1', '파는 물건', '파는 물건 상세정보', '직거래 환영', '파는 물건 설명', '2022-11-27', 'N', '2022-11-27', '3', 'Y');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '4', '나눠드릴게요 가져가세요', '3', '나눔 할 물건', '나눔 할 물건 상세정보', '택배거래', '나눔 할 물건 설명', '2022-12-03', 'N', '2022-12-03', '2', 'N');

INSERT INTO MARKET
(NO, MEMBER_NO, TITLE, MARKET_TYPE_NO, OBJECT_NAME, OBJECT_INFO, TRADE_METHOD, OBJECT_PS, ENROLL_DATE, DELETE_YN, MODIFY_DATE, HIT, TRADE_YN)
VALUES(SEQ_MARKET_NO.NEXTVAL, '5', '바꿀 사람 찾아요', '4', '바꿀 물건', '바꿀 물건 상세정보', '만나서 교환', '바꿀 물건 설명', '2022-12-15', 'N', '2022-12-15', '0', 'N');

--YeSS Market 사진 (20번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '20', '멜론.PNG', '멜론.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '20', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '20', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (19번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '19', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '19', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '19', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (18번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '18', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '18', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (17번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '17', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '17', '토마토.PNG', '토마토.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (16번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '16', '토마토.PNG', '토마토.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '16', '포도.PNG', '포도.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '16', '멜론.PNG', '멜론.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '16', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '16', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (15번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '15', '멜론.PNG', '멜론.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (14번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '14', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (13번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '13', '토마토.PNG', '토마토.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (12번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '12', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (11번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '11', '포도.PNG', '포도.PNG' ,'resources/upload/market', 'Y');

INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '10', '멜론.PNG', '멜론.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '10', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '10', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (9번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '9', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '9', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '9', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (8번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '8', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '8', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (7번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '7', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '7', '토마토.PNG', '토마토.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (6번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '토마토.PNG', '토마토.PNG' ,'resources/upload/market', 'Y');
--사진
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '포도.PNG', '포도.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '멜론.PNG', '멜론.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'N');
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '6', '수박.PNG', '수박.PNG' ,'resources/upload/market', 'N');

--YeSS Market 사진 (5번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '5', '멜론.PNG', '멜론.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (4번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '4', '복숭아.PNG', '복숭아.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (3번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '3', '토마토.PNG', '토마토.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (2번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '2', '자두.PNG', '자두.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 사진 (1번글)
--썸네일
INSERT INTO MARKET_ATTACHMENT
(NO, MARKET_NO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, THUMB_YN)
VALUES(SEQ_MARKET_ATTACHMENT_NO.NEXTVAL, '1', '포도.PNG', '포도.PNG' ,'resources/upload/market', 'Y');

--YeSS Market 댓글 (37번글)
INSERT INTO MARKET_CMT
(NO, MEMBER_NO, MARKET_NO, CMT)
VALUES(SEQ_MARKET_CMT_NO.NEXTVAL, 2, 37, '댓글댓글댓글');
INSERT INTO MARKET_CMT
(NO, MEMBER_NO, MARKET_NO, CMT)
VALUES(SEQ_MARKET_CMT_NO.NEXTVAL, 3, 37, '하하하하핳');

COMMIT;

SELECT
    MC.NO
    , MB.NICK
    , MC.MARKET_NO
    , MC.CMT
    , TO_CHAR(MC.MODIFY_DATE, 'yyyy-mm-dd') AS MODIFY_DATE
    , MC.SECRET_YN
FROM MARKET_CMT MC
JOIN MEMBER MB ON MC.MEMBER_NO = MB.NO;

