DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "RECYCLE" CASCADE CONSTRAINTS;
DROP TABLE "RECYCLE_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "RECYCLE_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "RECYCLE_LIKED" CASCADE CONSTRAINTS;


------------------------------------
-- MEMBER 테이블 생성
------------------------------------
CREATE TABLE "MEMBER" (
	"NO"	        NUMBER		                    NOT NULL,
	"GRADE_NO"	    NUMBER  DEFAULT 1	            NOT NULL,
	"ID"	        VARCHAR2(100)		            NOT NULL,
	"PWD"	        VARCHAR2(100)		            NOT NULL,
	"NAME"	        VARCHAR2(50)		            NOT NULL,
	"PHONE"	        CHAR(13)	    	            NOT NULL,
	"NICK"	        VARCHAR2(50)		            NOT NULL,
	"ADDR"	        VARCHAR2(500)		            NOT NULL,
	"ENROLL_DATE"	TIMESTAMP   DEFAULT SYSDATE     NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	    NOT NULL,
	"QUIT_YN"	    CHAR(1)	DEFAULT 'N' CHECK(QUIT_YN IN ('Y' , 'N'))	NOT NULL,
	"POINT"	        NUMBER	DEFAULT 0	            NOT NULL,
	"ADD_POINT"	    NUMBER	DEFAULT 0	            NOT NULL,
	"GRADE_DATE"	TIMESTAMP		                NULL
);
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;


COMMENT ON COLUMN "MEMBER"."NO" IS '회원번호';
COMMENT ON COLUMN "MEMBER"."GRADE_NO" IS '등급번호';
COMMENT ON COLUMN "MEMBER"."ID" IS '아이디';
COMMENT ON COLUMN "MEMBER"."PWD" IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."NAME" IS '이름';
COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호';
COMMENT ON COLUMN "MEMBER"."NICK" IS '닉네임';
COMMENT ON COLUMN "MEMBER"."ADDR" IS '주소';
COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '가입일자';
COMMENT ON COLUMN "MEMBER"."MODIFY_DATE" IS '최종수정일시';
COMMENT ON COLUMN "MEMBER"."QUIT_YN" IS '회원탈퇴여부';
COMMENT ON COLUMN "MEMBER"."POINT" IS '누적포인트';
COMMENT ON COLUMN "MEMBER"."ADD_POINT" IS '현재포인트';
COMMENT ON COLUMN "MEMBER"."GRADE_DATE" IS '등급변동일자';

--INSERT INTO 
--MEMBER (NO , ID , PWD , NAME , PHONE , NICK , ADDR)
--VALUES (SEQ_MEMBER_NO.NEXTVAL , 'user01' , '1234' , '우씨' ,'01012345678', 'nick01' , '서울시 금천구 시흥동');
commit;
select * from member;

--UPDATE
--    MEMBER
--SET
--    PHONE = #{phone}
--    , NICK = #{nick}
--    , ADDR = #{addr}
--WHERE
--    ID = #{id}

------------------------------------
-- RECYCLE 테이블 생성
------------------------------------
CREATE TABLE "RECYCLE" (
	"NO"	            NUMBER		                NOT NULL,
	"RECYCLE_TYPE_NO"	NUMBER		                NOT NULL,
	"NAME"	            VARCHAR2(50)		        NOT NULL,
	"RECYCLE_INFO"	    CLOB		                NOT NULL,
	"IMG_PATH"	        VARCHAR2(50)		        NULL,
	"ENROLL_DATE"	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	        CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('N', 'Y'))	NULL
);
DROP SEQUENCE SEQ_RECYCLE_NO;
CREATE SEQUENCE SEQ_RECYCLE_NO NOCACHE NOCYCLE;

COMMENT ON COLUMN "RECYCLE"."NO" IS '분리수거번호';
COMMENT ON COLUMN "RECYCLE"."RECYCLE_TYPE_NO" IS '분리수거유형번호';
COMMENT ON COLUMN "RECYCLE"."NAME" IS '분리수거명';
COMMENT ON COLUMN "RECYCLE"."RECYCLE_INFO" IS '재활용방법';
COMMENT ON COLUMN "RECYCLE"."IMG_PATH" IS '이미지경로';
COMMENT ON COLUMN "RECYCLE"."ENROLL_DATE" IS '등록일자';
COMMENT ON COLUMN "RECYCLE"."MODIFY_DATE" IS '최종수정일자';
COMMENT ON COLUMN "RECYCLE"."DELETE_YN" IS '삭제여부';


------------------------------------
-- RECYCLE_ATTACHMENT 테이블 생성
------------------------------------
CREATE TABLE "RECYCLE_ATTACHMENT" (
	"NO"	        NUMBER		                NOT NULL,
	"RECYCLE_NO"	NUMBER		                NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		        NOT NULL,
	"CHANGE_NAME"	VARCHAR2(255)		        NOT NULL,
	"FILE_PATH"	    VARCHAR2(1000)		        NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	    CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN('N', 'Y'))	NOT NULL,
	"STATUS"	    CHAR(1)	DEFAULT 'O' CHECK(STATUS IN ('O', 'X'))	NOT NULL
);
DROP SEQUENCE SEQ_RECYCLE_ATTACHMENT_NO;
CREATE SEQUENCE SEQ_RECYCLE_ATTACHMENT_NO NOCACHE NOCYCLE;

COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."NO" IS '사진 번호';
COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."RECYCLE_NO" IS '분리수거번호';
COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."ORIGIN_NAME" IS '기존파일명';
COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."CHANGE_NAME" IS '바뀐파일명';
COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."FILE_PATH" IS '파일경로';
COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."ENROLL_DATE" IS '업로드일시';
COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."THUMB_YN" IS '썸네일여부';
COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."STATUS" IS '상태';


------------------------------------
-- RECYCLE_TYPE 테이블 생성
------------------------------------
CREATE TABLE "RECYCLE_TYPE" (
	"NO"	NUMBER		    NOT NULL,
	"TYPE"	VARCHAR2(100)	NOT NULL
);
DROP SEQUENCE SEQ_RECYCLE_TYPE_NO;
CREATE SEQUENCE SEQ_RECYCLE_TYPE_NO NOCACHE NOCYCLE;

COMMENT ON COLUMN "RECYCLE_TYPE"."NO" IS '분리수거유형번호';
COMMENT ON COLUMN "RECYCLE_TYPE"."TYPE" IS '분리수거유형';


------------------------------------
-- RECYCLE_LIKED 테이블 생성
------------------------------------
CREATE TABLE "RECYCLE_LIKED" (
	"MEMBER_NO"	    NUMBER		NOT NULL,
	"RECYCLE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECYCLE_LIKED"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "RECYCLE_LIKED"."RECYCLE_NO" IS '분리수거번호';


COMMIT;