--瘤款 基敲

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'力格5' ,'郴侩5' );


INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'力格5' ,'郴侩5' );


INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'力格' ,'郴侩' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'力格2' ,'郴侩2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'力格3' ,'郴侩3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'力格4' ,'郴侩4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'力格5' ,'郴侩5' );


COMMIT;