INSERT INTO GRADE VALUES(1,'¾¾¾Ñ');
INSERT INTO GRADE VALUES(2,'»õ½Ï');
INSERT INTO GRADE VALUES(3,'°¡Áö');
INSERT INTO GRADE VALUES(4,'²ÉÀÙ');
INSERT INTO GRADE VALUES(5,'¿·¸Å');
INSERT INTO GRADE VALUES(8,'ºñ·á');
INSERT INTO GRADE VALUES(9,'°ü¸®ÀÚ');

INSERT INTO NEWS_TYPE VALUES(1,'RECYCLE NEWS');
INSERT INTO NEWS_TYPE VALUES(2,'RECYCLE AREA');
INSERT INTO NEWS_TYPE VALUES(3,'UPDATE NOTICE');

INSERT INTO MEMBER( NO,GRADE_NO,ID ,PWD,NAME,PHONE ,NICK ,ADDR ) VALUES ( SEQ_MEMBER_NO.NEXTVAL ,9 ,'ADMIN' ,'1234' ,'ADMIN' ,'010-1010-1010' ,'ADMIN' ,'ADDRESS' );
COMMIT;