---------------------------
--NEWS
---------------------------
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'제목' ,'내용' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'제목2' ,'내용2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'제목3' ,'내용3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'제목4' ,'내용4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,1 ,'제목5' ,'내용5' );

-- AREA

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'그물코 친환경카페' ,'괜찮은 친환경 카페' );
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '그물코 친환경카페', '서울 양천구 목동동로10길','16-23');
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'카페찹스 구로점' ,'괜찮은 친환경 카페' );
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '카페찹스 구로점', '서울 구로구 공원로6가길 52','1층');
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'보틀 팩토리' ,'괜찮은 친환경 카페' );
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '논현동', '서울시 강남구 논현동','1층');
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'그물코 친환경카페' ,'괜찮은 친환경 카페' );
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '청담동', '서울시 강남구 청담동','1층');
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'1.5도씨' ,'괜찮은 친환경 카페' );
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '삼성동', '서울시 강남구 삼성동','1층');
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'에코브런치' ,'내용3' );
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '대치동', '서울시 강남구 대치동','1층');
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'THIS IS TITLE' ,'괜찮은 친환경 카페' );
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '역삼동', '서울시 강남구 역삼동','1층');
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'제목4' ,'내용4' );
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '도곡동', '서울시 강남구 도곡동','1층');
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'THIS IS TITLE' ,'괜찮은 친환경 카페' );
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '개포동', '서울시 강남구 개포동','1층');
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,2 ,'제목5' ,'내용5' );
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '수서동', '서울시 강남구 수서동','1층');

-- UPDATE

INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'제목' ,'내용' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'제목2' ,'내용2' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'제목3' ,'내용3' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'제목4' ,'내용4' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'THIS IS TITLE' ,'THIS IS CONTENT' );
INSERT INTO NEWS ( NO , ADMIN_NO , NEWS_TYPE_NO , TITLE , CONTENT ) VALUES ( SEQ_NEWS_NO.NEXTVAL ,1 ,3 ,'제목5' ,'내용5' );
ROLLBACK;