DROP TABLE "WHERE_TO" CASCADE CONSTRAINTS;


DROP SEQUENCE SEQ_WHERE_TO_NO;
CREATE SEQUENCE SEQ_WHERE_TO_NO NOCYCLE;

CREATE TABLE "WHERE_TO" (
	"NO"	NUMBER		NOT NULL,
	"NEWS_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR(50)		NOT NULL,
	"ADDRESS"	VARCHAR(400)		NOT NULL,
    "ADDR_DETAIL"	VARCHAR(400)
);

COMMENT ON COLUMN "WHERE_TO"."NO" IS '지역 번호';

COMMENT ON COLUMN "WHERE_TO"."NAME" IS '장소 이름';

COMMENT ON COLUMN "WHERE_TO"."ADDRESS" IS '주소';

COMMENT ON COLUMN "WHERE_TO"."ADDR_DETAIL" IS '상세주소';

ALTER TABLE "WHERE_TO" ADD CONSTRAINT "PK_WHERE_TO" PRIMARY KEY (
	"NO"
);

ALTER TABLE "WHERE_TO" ADD CONSTRAINT "FK_NEWS_TO_WHERE_TO_1" FOREIGN KEY (
	"NEWS_NO"
)
REFERENCES "NEWS" (
	"NO"
);



--INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '장소이름', '서울시 강남구 역삼동');

INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 111, '신사동', '서울시 강남구 신사동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 112, '압구정동', '서울시 강남구 압구정동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 113, '논현동', '서울시 강남구 논현동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 114, '청담동', '서울시 강남구 청담동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 115, '삼성동', '서울시 강남구 삼성동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 116, '대치동', '서울시 강남구 대치동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 117, '역삼동', '서울시 강남구 역삼동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 118, '도곡동', '서울시 강남구 도곡동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 119, '개포동', '서울시 강남구 개포동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 120, '수서동', '서울시 강남구 수서동','502호');
COMMIT;

SELECT COUNT(*)
FROM MEMBER
WHERE ID='user01';

SELECT 
    W.NO
    ,NEWS_NO
    ,NAME
    ,ADDRESS
    ,ADDR_DETAIL
    ,DELETE_YN
FROM WHERE_TO W
JOIN NEWS N ON N.NO = W.NEWS_NO
WHERE DELETE_YN = 'N'
;

SELECT
    NO AS PLACE_NO
    ,NAME
    ,ADDRESS
    ,ADDR_DETAIL
FROM WHERE_TO
WHERE NEWS_NO = #{no}
