DROP TABLE "WHERE_TO" CASCADE CONSTRAINTS;


DROP SEQUENCE SEQ_WHERE_TO_NO;
CREATE SEQUENCE SEQ_WHERE_TO_NO NOCYCLE;

CREATE TABLE "WHERE_TO" (
	"NO"	NUMBER		NOT NULL,
	"NEWS_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR(50)		NOT NULL,
	"ADDRESS"	VARCHAR(400)		NOT NULL,
    "ADDR_DETAIL"	VARCHAR(400)
);

COMMENT ON COLUMN "WHERE_TO"."NO" IS '지역 번호';

COMMENT ON COLUMN "WHERE_TO"."NAME" IS '장소 이름';

COMMENT ON COLUMN "WHERE_TO"."ADDRESS" IS '주소';

COMMENT ON COLUMN "WHERE_TO"."ADDR_DETAIL" IS '상세주소';

ALTER TABLE "WHERE_TO" ADD CONSTRAINT "PK_WHERE_TO" PRIMARY KEY (
	"NO"
);

ALTER TABLE "WHERE_TO" ADD CONSTRAINT "FK_NEWS_TO_WHERE_TO_1" FOREIGN KEY (
	"NEWS_NO"
)
REFERENCES "NEWS" (
	"NO"
);



--INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, SEQ_NEWS_NO.CURRVAL, '장소이름', '서울시 강남구 역삼동');

INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 111, '장소이름', '서울시 강남구 역삼동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 112, '장소이름', '서울시 강남구 역삼동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 113, '장소이름', '서울시 강남구 역삼동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 114, '장소이름', '서울시 강남구 역삼동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 115, '장소이름', '서울시 강남구 역삼동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 116, '장소이름', '서울시 강남구 역삼동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 117, '장소이름', '서울시 강남구 역삼동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 118, '장소이름', '서울시 강남구 역삼동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 119, '장소이름', '서울시 강남구 역삼동','502호');
INSERT INTO WHERE_TO VALUES(SEQ_WHERE_TO_NO.NEXTVAL, 120, '장소이름', '서울시 강남구 역삼동','502호');
COMMIT;

SELECT COUNT(*)
FROM MEMBER
WHERE ID='user01';