DROP TABLE "WHERE_TO" CASCADE CONSTRAINTS;


DROP SEQUENCE SEQ_WHERE_TO_NO;
CREATE SEQUENCE SEQ_WHERE_TO NOCYCLE;

CREATE TABLE "WHERE_TO" (
	"NO"	NUMBER		NOT NULL,
	"NEWS_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR(50)		NOT NULL,
	"ADDRESS"	VARCHAR(400)		NOT NULL
);

COMMENT ON COLUMN "WHERE_TO"."NO" IS '지역 번호';

COMMENT ON COLUMN "WHERE_TO"."NAME" IS '장소 이름';

COMMENT ON COLUMN "WHERE_TO"."ADDRESS" IS '주소';

ALTER TABLE "WHERE_TO" ADD CONSTRAINT "PK_WHERE_TO" PRIMARY KEY (
	"NO"
);

ALTER TABLE "WHERE_TO" ADD CONSTRAINT "FK_NEWS_TO_WHERE_TO_1" FOREIGN KEY (
	"NEWS_NO"
)
REFERENCES "NEWS" (
	"NO"
);
