select * from yessmall_prod;

--상품목록조회
SELECT P.PROD_NO, P.PROD_CATE_NO, P.PROD_NAME, P.PROD_PRICE, A.PROD_IMG_NO, A.THUMB_YN, A.CHANGE_NAME
FROM YESSMALL_PROD P
JOIN YESSMALL_ATTACHMENT A
ON P.PROD_NO = A.PROD_NO
WHERE A.THUMB_YN = 'Y'
ORDER BY PROD_NO DESC
;

--상품상세조회
SELECT P.PROD_NO, P.PROD_CATE_NO, P.PROD_NAME, P.PROD_INFO, P.PROD_DETAIL, P.PROD_PRICE, P.PROD_STOCK, A.PROD_IMG_NO, A.THUMB_YN
FROM YESSMALL_PROD P
JOIN YESSMALL_ATTACHMENT A
ON P.PROD_NO = A.PROD_NO
WHERE P.PROD_NO = 
ORDER BY PROD_NO DESC
;

--리스트
SELECT P.PROD_NO, P.PROD_CATE_NO, P.PROD_NAME, P.PROD_PRICE, A.PROD_IMG_NO, A.THUMB_YN, A.CHANGE_NAME
FROM YESSMALL_PROD P
JOIN YESSMALL_ATTACHMENT A
ON P.PROD_NO = A.PROD_NO
JOIN YESSMALL_CATEGORY C
ON P.PROD_CATE_NO = C.PROD_CATE_NO
--WHERE A.THUMB_YN = 'Y'


   -- AND P.PROD_CATE_NO = ${category}

--AND P.PROD_NAME LIKE 
ORDER BY P.PROD_NO DESC;

SELECT P.PROD_NO, P.PROD_CATE_NO, P.PROD_NAME, P.PROD_PRICE, A.PROD_IMG_NO, A.THUMB_YN, A.CHANGE_NAME
FROM YESSMALL_PROD P
JOIN YESSMALL_ATTACHMENT A
ON P.PROD_NO = A.PROD_NO
JOIN YESSMALL_CATEGORY C
ON P.PROD_CATE_NO = C.PROD_CATE_NO
WHERE A.THUMB_YN = 'Y'
;


SELECT R.RV_NO, R.PROD_NO, R.TITLE, R.CONTENT, R.ENROLL_DATE, R.MODIFY_DATE, R.DELETE_YN, M.NICK
FROM YESSMALL_REVIEW R
JOIN MEMBER M
ON M.NO = R.MEMBER_NO
WHERE R.PROD_NO = 1
AND R.DELETE_YN = 'N';

INSERT INTO MEMBER( NO,GRADE_NO,ID ,PWD,NAME,PHONE ,NICK ,ADDR ) VALUES ( SEQ_MEMBER_NO.NEXTVAL ,9 ,'ADMIN' ,'1234' ,'ADMIN' ,'010-1010-1010' ,'ADMIN' ,'ADDRESS' );

commit;
