--------------------------------------------------------------------------
--DROP TABLE--------------------------------------------------------------
--------------------------------------------------------------------------
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "COMM" CASCADE CONSTRAINTS;
DROP TABLE "REPORT" CASCADE CONSTRAINTS;
DROP TABLE "NEWS" CASCADE CONSTRAINTS;
DROP TABLE "REPORT_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "QNA" CASCADE CONSTRAINTS;
DROP TABLE "RECYCLE" CASCADE CONSTRAINTS;
DROP TABLE "CART" CASCADE CONSTRAINTS;
DROP TABLE "GRADE" CASCADE CONSTRAINTS;
DROP TABLE "ORDER" CASCADE CONSTRAINTS;
DROP TABLE "PAYMENT" CASCADE CONSTRAINTS;
DROP TABLE "ATTEND" CASCADE CONSTRAINTS;
DROP TABLE "FAQ" CASCADE CONSTRAINTS;
DROP TABLE "RECYCLE_LIKED" CASCADE CONSTRAINTS;
DROP TABLE "YESSMALL_PROD" CASCADE CONSTRAINTS;
DROP TABLE "YESSMALL_REVIEW" CASCADE CONSTRAINTS;
DROP TABLE "YESSMALL_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "YESSMALL_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "MARKET" CASCADE CONSTRAINTS;
DROP TABLE "MARKET_CMT" CASCADE CONSTRAINTS;
DROP TABLE "MARKET_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "RECYCLE_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "COMM_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "POINT_HISTORY" CASCADE CONSTRAINTS;
DROP TABLE "COMM_CATE" CASCADE CONSTRAINTS;
DROP TABLE "COMM_LIKE" CASCADE CONSTRAINTS;
DROP TABLE "ORDER_DETAIL" CASCADE CONSTRAINTS;
DROP TABLE "ZZIM" CASCADE CONSTRAINTS;
DROP TABLE "YESS_LIKED" CASCADE CONSTRAINTS;
DROP TABLE "POINT_PLACE" CASCADE CONSTRAINTS;
DROP TABLE "NEWS_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "QNA_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "REPORT_BOARD_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "MARKET_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "YESSMALL_REVIEW_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "RECYCLE_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "COMM_CMT" CASCADE CONSTRAINTS;
DROP TABLE "COMM_HASHTAG" CASCADE CONSTRAINTS;
DROP TABLE "HASHTAG" CASCADE CONSTRAINTS;

COMMIT;

--------------------------------------------------------------------------
--DROP/CREATE SEQUENCE----------------------------------------------------
--------------------------------------------------------------------------
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCYCLE;
DROP SEQUENCE SEQ_COMMUNITY_NO;
CREATE SEQUENCE SEQ_COMMUNITY_NO NOCYCLE;
DROP SEQUENCE SEQ_REPORT_NO;
CREATE SEQUENCE SEQ_REPORT_NO NOCYCLE;
DROP SEQUENCE SEQ_NEWS_NO;
CREATE SEQUENCE SEQ_NEWS_NO NOCYCLE;
DROP SEQUENCE SEQ_REPORT_TYPE_NO;
CREATE SEQUENCE SEQ_REPORT_TYPE_NO NOCYCLE;
DROP SEQUENCE SEQ_QNA_NO;
CREATE SEQUENCE SEQ_QNA_NO NOCYCLE;
DROP SEQUENCE SEQ_RECYCLE_NO;
CREATE SEQUENCE SEQ_RECYCLE_NO NOCYCLE;
DROP SEQUENCE SEQ_CART_NO;
CREATE SEQUENCE SEQ_CART_NO NOCYCLE;
DROP SEQUENCE SEQ_GRADE_NO;
CREATE SEQUENCE SEQ_GRADE_NO NOCYCLE;
DROP SEQUENCE SEQ_ORDER_NO;
CREATE SEQUENCE SEQ_ORDER_NO NOCYCLE;
DROP SEQUENCE SEQ_PAYMENT_NO;
CREATE SEQUENCE SEQ_PAYMENT_NO NOCYCLE;
DROP SEQUENCE SEQ_ATTEND_NO;
CREATE SEQUENCE SEQ_ATTEND_NO NOCYCLE;
DROP SEQUENCE SEQ_FAQ_NO;
CREATE SEQUENCE SEQ_FAQ_NO NOCYCLE;
DROP SEQUENCE SEQ_RECYCLE_LIKED_NO;
CREATE SEQUENCE SEQ_RECYCLE_LIKED_NO NOCYCLE;
DROP SEQUENCE SEQ_ATTEND_NO;
CREATE SEQUENCE SEQ_ATTEND_NO NOCYCLE;
DROP SEQUENCE SEQ_YESSMALL_PROD_NO;
CREATE SEQUENCE SEQ_YESSMALL_PROD_NO NOCYCLE;
DROP SEQUENCE SEQ_YESSMALL_REVIEW_NO;
CREATE SEQUENCE SEQ_YESSMALL_REVIEW_NO NOCYCLE;
DROP SEQUENCE SEQ_PROD_CATE_NO;
CREATE SEQUENCE SEQ_PROD_CATE_NO NOCYCLE;
DROP SEQUENCE SEQ_YESSMALL_ATTACHMENT_NO;
CREATE SEQUENCE SEQ_YESSMALL_ATTACHMENT_NO NOCYCLE;
DROP SEQUENCE SEQ_MARKET_NO;
CREATE SEQUENCE SEQ_MARKET_NO NOCYCLE;
DROP SEQUENCE SEQ_MARKET_CMT_NO;
CREATE SEQUENCE SEQ_MARKET_CMT_NO NOCYCLE;
DROP SEQUENCE SEQ_MARKET_TYPE_NO;
CREATE SEQUENCE SEQ_MARKET_TYPE_NO NOCYCLE;
DROP SEQUENCE SEQ_RECYCLE_TYPE_NO;
CREATE SEQUENCE SEQ_RECYCLE_TYPE_NO NOCYCLE;
DROP SEQUENCE SEQ_COMM_ATTACHMENT_NO;
CREATE SEQUENCE SEQ_COMM_ATTACHMENT_NO NOCYCLE;
DROP SEQUENCE SEQ_POINT_HISTORY_NO;
CREATE SEQUENCE SEQ_POINT_HISTORY_NO NOCYCLE;
DROP SEQUENCE SEQ_COMM_CATE_NO;
CREATE SEQUENCE SEQ_COMM_CATE_NO NOCYCLE;
DROP SEQUENCE SEQ_COMM_LIKE_NO;
CREATE SEQUENCE SEQ_COMM_LIKE_NO NOCYCLE;
DROP SEQUENCE SEQ_ORDER_DETAIL_NO;
CREATE SEQUENCE SEQ_ORDER_DETAIL_NO NOCYCLE;
DROP SEQUENCE SEQ_ZZIM_NO;
CREATE SEQUENCE SEQ_ZZIM_NO NOCYCLE;
DROP SEQUENCE SEQ_YESS_LIKED_NO;
CREATE SEQUENCE SEQ_YESS_LIKED_NO NOCYCLE;
DROP SEQUENCE SEQ_POINT_PLACE_NO;
CREATE SEQUENCE SEQ_POINT_PLACE_NO NOCYCLE;
DROP SEQUENCE SEQ_NEWS_TYPE_NO;
CREATE SEQUENCE SEQ_NEWS_TYPE_NO NOCYCLE;
DROP SEQUENCE SEQ_QNA_TYPE_NO;
CREATE SEQUENCE SEQ_QNA_TYPE_NO NOCYCLE;
DROP SEQUENCE SEQ_REPORT_BOARD_TYPE_NO;
CREATE SEQUENCE SEQ_REPORT_BOARD_TYPE_NO NOCYCLE;
DROP SEQUENCE SEQ_MARKET_ATTACHMENT_NO;
CREATE SEQUENCE SEQ_MARKET_ATTACHMENT_NO NOCYCLE;
DROP SEQUENCE SEQ_YESSMALL_REVIEW_ATTACHMENT_NO;
CREATE SEQUENCE SEQ_YESSMALL_REVIEW_ATTACHMENT_NO NOCYCLE;
DROP SEQUENCE SEQ_RECYCLE_ATTACHMENT_NO;
CREATE SEQUENCE SEQ_RECYCLE_ATTACHMENT_NO NOCYCLE;
DROP SEQUENCE SEQ_COMM_CMT_NO;
CREATE SEQUENCE SEQ_COMM_CMT_NO NOCYCLE;

COMMIT;

--------------------------------------------------------------------------
--CREATE TABLE------------------------------------------------------------
--------------------------------------------------------------------------
CREATE TABLE "MEMBER" (
	"NO"	NUMBER		NOT NULL,
	"GRADE_NO"	NUMBER	DEFAULT 1	NOT NULL,
	"ID"	VARCHAR2(50)		NOT NULL,
	"PWD"	VARCHAR2(50)		NOT NULL,
	"NAME"	VARCHAR2(50)		NOT NULL,
	"PHONE"	CHAR(13)		NOT NULL,
	"NICK"	VARCHAR2(50)		NOT NULL,
	"ADDR"	VARCHAR2(500)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"QUIT_YN"	CHAR(1)	DEFAULT 'N' CHECK(QUIT_YN IN ('Y' , 'N'))	NOT NULL,
	"POINT"	NUMBER	DEFAULT 0	NOT NULL,
	"ADD_POINT"	NUMBER	DEFAULT 0	NOT NULL,
	"GRADE_DATE"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "MEMBER"."NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."GRADE_NO" IS '등급번호';

COMMENT ON COLUMN "MEMBER"."ID" IS '아이디';

COMMENT ON COLUMN "MEMBER"."PWD" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."NICK" IS '닉네임';

COMMENT ON COLUMN "MEMBER"."ADDR" IS '주소';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '가입일자';

COMMENT ON COLUMN "MEMBER"."MODIFY_DATE" IS '최종수정일시';

COMMENT ON COLUMN "MEMBER"."QUIT_YN" IS '회원탈퇴여부';

COMMENT ON COLUMN "MEMBER"."POINT" IS '누적포인트';

COMMENT ON COLUMN "MEMBER"."ADD_POINT" IS '현재포인트';

COMMENT ON COLUMN "MEMBER"."GRADE_DATE" IS '등급변동일자';

CREATE TABLE "COMM" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMUNITY_TYPE_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONT"	VARCHAR2(4000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"HIT"	NUMBER	DEFAULT 0	NOT NULL,
	"PICK_YN"	CHAR(1)	DEFAULT 'N' CHECK(PICK_YN IN ('Y' , 'N'))	NOT NULL,
	"LIKE_CNT"	NUMBER		NOT NULL,
	"HASHTAG"	VARCHAR2(4000)		NULL	
);

COMMENT ON COLUMN "COMM"."NO" IS '글번호';

COMMENT ON COLUMN "COMM"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "COMM"."TITLE" IS '글제목';

COMMENT ON COLUMN "COMM"."CONTENT" IS '글내용';

COMMENT ON COLUMN "COMM"."ENROLL_DATE" IS '작성일시';

COMMENT ON COLUMN "COMM"."DELETE_YN" IS '삭제여부
체크제약조건';

COMMENT ON COLUMN "COMM"."MODIFY_DATE" IS '최종수정일시';


CREATE TABLE "REPORT" (
	"NO"	NUMBER		NOT NULL,
	"REPORT_TYPE_NO"	NUMBER		NOT NULL,
	"RE_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"REPORT_TIME"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'O' CHECK(STATUS IN('O', 'X'))	NOT NULL,
	"REPORT_CONT"	VARCHAR(2000)		NOT NULL
);

COMMENT ON COLUMN "REPORT"."RE_NO" IS '회원번호';


CREATE TABLE "NEWS" (
	"NO"	NUMBER		NOT NULL,
	"ADMIN_NO"	NUMBER	DEFAULT 1	NOT NULL,
	"NOTICE_TYPE_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "NEWS"."ADMIN_NO" IS '회원번호(관리자전용)';

COMMENT ON COLUMN "NEWS"."NOTICE_TYPE_NO" IS '카테고리 번호';

COMMENT ON COLUMN "NEWS"."TITLE" IS '글 제목';

COMMENT ON COLUMN "NEWS"."CONTENT" IS '글내용';

COMMENT ON COLUMN "NEWS"."ENROLL_DATE" IS '작성일자';

COMMENT ON COLUMN "NEWS"."DELETE_YN" IS '삭제여부';

COMMENT ON COLUMN "NEWS"."MODIFY_DATE" IS '수정일자';


CREATE TABLE "REPORT_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"TYPE"	VARCHAR2(10)		NOT NULL
);


CREATE TABLE "QNA" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"QNA_TYPE_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"ANSWER"	VARCHAR2(1000)		NULL,
	"ANSWER_DATE"	TIMESTAMP		NULL,
	"ANSWER_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL
);

COMMENT ON COLUMN "QNA"."NO" IS '글번호';

COMMENT ON COLUMN "QNA"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "QNA"."QNA_TYPE_NO" IS '카테고리 번호';

COMMENT ON COLUMN "QNA"."TITLE" IS '글제목';

COMMENT ON COLUMN "QNA"."CONTENT" IS '글내용';

COMMENT ON COLUMN "QNA"."ENROLL_DATE" IS '작성일시';

COMMENT ON COLUMN "QNA"."DELETE_YN" IS '삭제여부
체크제약조건';

COMMENT ON COLUMN "QNA"."MODIFY_DATE" IS '최종수정일시';

COMMENT ON COLUMN "QNA"."ANSWER_YN" IS '답변여부';


CREATE TABLE "RECYCLE" (
	"NO"	NUMBER		NOT NULL,
	"RECYCLE_TYPE_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(50)		NOT NULL,
	"RECYCLE_INFO"	CLOB		NOT NULL,
	"IMG_PATH"	VARCHAR2(50)		NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(STATUS IN ('N', 'Y'))	NULL
);


CREATE TABLE "CART" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"YESS_MALL_NO"	NUMBER		NOT NULL,
	"CNT"	NUMBER		NOT NULL,
	"PAYMENT_YN"	CHAR(1)	DEFAULT 'N' CHECK(PAYMENT_YN IN ('Y' , 'N'))	NOT NULL,
	"ADD_DATE"	TIMESTMAP	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "CART"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "CART"."CNT" IS '수량';

COMMENT ON COLUMN "CART"."PAYMENT_YN" IS '구매여부';

COMMENT ON COLUMN "CART"."ADD_DATE" IS '담은날짜';


CREATE TABLE "GRADE" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "GRADE"."NO" IS '등급번호';

COMMENT ON COLUMN "GRADE"."NAME" IS '등급이름';


CREATE TABLE "ORDER" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PLUS_POINT"	NUMBER		NOT NULL,
	"USE_POINT"	NUMBER	DEFAULT 0	NULL,
	"SUM_PRICE"	NUMBER		NOT NULL,
	"CANCEL_YN"	CHAR(1)	DEFAULT 'N' CHECK(CANCEL_YN IN ('Y' , 'N'))	NOT NULL,
	"NAME"	VARCHAR(20)		NULL,
	"ADDRESS"	VARCHAR(100)		NULL,
	"PHONE"	CHAR(13)		NULL
);

COMMENT ON COLUMN "ORDER"."NO" IS '주문번호';

COMMENT ON COLUMN "ORDER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "ORDER"."PLUS_POINT" IS '적립포인트';

COMMENT ON COLUMN "ORDER"."USE_POINT" IS '사용포인트';

COMMENT ON COLUMN "ORDER"."SUM_PRICE" IS '합산 금액';

COMMENT ON COLUMN "ORDER"."CANCEL_YN" IS '주문상태';


CREATE TABLE "PAYMENT" (
	"NO"	NUMBER		NOT NULL,
	"ORDER_NO"	NUMBER		NOT NULL,
	"PAYMENT"	VARCHAR2(30)		NOT NULL,
	"PAY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"CANCEL_YN"	CHAR(1)	DEFAULT 'N' CHECK(CANCEL_YN IN ('Y' , 'N'))	NOT NULL,
	"CANCEL_DATE"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "PAYMENT"."NO" IS '결제번호';

COMMENT ON COLUMN "PAYMENT"."ORDER_NO" IS '주문번호';

COMMENT ON COLUMN "PAYMENT"."PAYMENT" IS '결제수단';

COMMENT ON COLUMN "PAYMENT"."PAY_DATE" IS '결제날짜';

COMMENT ON COLUMN "PAYMENT"."CANCEL_YN" IS '취소여부';

COMMENT ON COLUMN "PAYMENT"."CANCEL_DATE" IS '취소날짜';


CREATE TABLE "ATTEND" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ATTEND_DATE"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "ATTEND"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "ATTEND"."ATTEND_DATE" IS '출석일자';


CREATE TABLE "FAQ" (
	"NO"	NUMBER		NOT NULL,
	"QNA_TYPE_NO"	NUMBER		NOT NULL,
	"ADMIN_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "FAQ"."NO" IS 'SEQUENCE';

COMMENT ON COLUMN "FAQ"."QNA_TYPE_NO" IS '카테고리 번호';

COMMENT ON COLUMN "FAQ"."ADMIN_NO" IS '회원번호';

COMMENT ON COLUMN "FAQ"."TITLE" IS '글제목';

COMMENT ON COLUMN "FAQ"."CONTENT" IS '글내용';

COMMENT ON COLUMN "FAQ"."ENROLL_DATE" IS '작성일자';


CREATE TABLE "RECYCLE_LIKED" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"RECYCLE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECYCLE_LIKED"."MEMBER_NO" IS '회원번호';


CREATE TABLE "YESSMALL_PROD" (
	"PROD_NO"	NUMBER		NOT NULL,
	"PROD_CATE_NO"	NUMBER		NOT NULL,
	"PROD_NAME"	VARCHAR2(50)		NOT NULL,
	"PROD_INFO"	VARCHAR2(4000)		NOT NULL,
	"PROD_DETAIL"	CLOB		NOT NULL,
	"PROD_PRICE"	NUMBER		NOT NULL,
	"PROD_STOCK"	NUMBER	DEFAULT 100	NOT NULL
);

COMMENT ON COLUMN "YESSMALL_PROD"."PROD_NAME" IS '이름';

COMMENT ON COLUMN "YESSMALL_PROD"."PROD_INFO" IS '제품 소개';

COMMENT ON COLUMN "YESSMALL_PROD"."PROD_DETAIL" IS '제품 상세 소개';

COMMENT ON COLUMN "YESSMALL_PROD"."PROD_PRICE" IS '가격';

COMMENT ON COLUMN "YESSMALL_PROD"."PROD_STOCK" IS '재고 수량';


CREATE TABLE "YESSMALL_REVIEW" (
	"RV_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PROD_NO"	NUMBER		NOT NULL,
	 "TITLE"     VARCHAR2(300) NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL
);

COMMENT ON COLUMN "YESSMALL_REVIEW"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "YESSMALL_REVIEW"."DELETE_YN" IS '삭제여부';


CREATE TABLE "YESSMALL_CATEGORY" (
	"PROD_CATE_NO"	NUMBER		NOT NULL,
	"PROD_CATEGORY"	VARCHAR2(15)		NOT NULL
);

COMMENT ON COLUMN "YESSMALL_CATEGORY"."PROD_CATEGORY" IS '상품 분류';


CREATE TABLE "YESSMALL_ATTACHMENT" (
	"PROD_IMG_NO"	NUMBER		NOT NULL,
	"PROD_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN('N','Y'))	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'O' CHECK(STATUS IN ('O', 'X'))	NOT NULL
);

COMMENT ON COLUMN "YESSMALL_ATTACHMENT"."ORIGIN_NAME" IS '기존 이름';

COMMENT ON COLUMN "YESSMALL_ATTACHMENT"."CHANGE_NAME" IS '변경된 이름';

COMMENT ON COLUMN "YESSMALL_ATTACHMENT"."FILE_PATH" IS '파일 경로';

COMMENT ON COLUMN "YESSMALL_ATTACHMENT"."ENROLL_DATE" IS '등록 일시';

COMMENT ON COLUMN "YESSMALL_ATTACHMENT"."THUMB_YN" IS '썸네일 여부';

COMMENT ON COLUMN "YESSMALL_ATTACHMENT"."STATUS" IS '상태';


CREATE TABLE "MARKET" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MARKET_TYPE_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(100)		NULL,
	"OBJECT_NAME"	VARCHAR2(100)		NOT NULL,
	"OBJECT_INFO"	VARCHAR2(100)		NOT NULL,
	"TRADE_METHOD"	VARCHAR2(100)		NOT NULL,
	"OBJECT_PS"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"HIT"	NUMBER	DEFAULT 0	NOT NULL,
	"TRADE_YN"	CHAR(1)	DEFAULT 'N' CHECK(TRADE_YN IN ('Y' , 'N'))	NOT NULL
);

COMMENT ON COLUMN "MARKET"."NO" IS '글번호';

COMMENT ON COLUMN "MARKET"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MARKET"."ENROLL_DATE" IS '작성일시';

COMMENT ON COLUMN "MARKET"."DELETE_YN" IS '삭제여부';

COMMENT ON COLUMN "MARKET"."MODIFY_DATE" IS '최종수정일시';

COMMENT ON COLUMN "MARKET"."HIT" IS '조회수';


CREATE TABLE "MARKET_CMT" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MARKET_NO"	NUMBER		NOT NULL,
	"CMT"	VARCHAR2(300)		NOT NULL,
	"CMT_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"SECRET_YN"	CHAR(1)	DEFAULT 'N' CHECK(SECRET_YN IN ('Y' , 'N'))	NOT NULL
);

COMMENT ON COLUMN "MARKET_CMT"."NO" IS '자유게시판 댓글 번호';

COMMENT ON COLUMN "MARKET_CMT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MARKET_CMT"."MARKET_NO" IS '글번호';

COMMENT ON COLUMN "MARKET_CMT"."CMT" IS '댓글 내용';

COMMENT ON COLUMN "MARKET_CMT"."CMT_DATE" IS '작성 날짜';

COMMENT ON COLUMN "MARKET_CMT"."DELETE_YN" IS '삭제 여부';

COMMENT ON COLUMN "MARKET_CMT"."MODIFY_DATE" IS '최종 수정 일시';


CREATE TABLE "MARKET_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"MARKET_TYPE"	VARCHAR2(10)		NOT NULL
);


CREATE TABLE "RECYCLE_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"TYPE"	VARCHAR2(100)		NOT NULL
);


CREATE TABLE "COMM_ATTACHMENT" (
	"NO"	NUMBER		NOT NULL,
	"COMMUNITY_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN('N', 'Y'))	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'O' CHECK(STATUS IN ('O', 'X'))	NOT NULL
);

COMMENT ON COLUMN "COMM_ATTACHMENT"."COMMUNITY_NO" IS '글번호';


CREATE TABLE "POINT_HISTORY" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"TIME_REPORT"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"POINT"	NUMBER		NOT NULL,
	"POINT_PLACE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "POINT_HISTORY"."NO" IS '포인트내역번호';

COMMENT ON COLUMN "POINT_HISTORY"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "POINT_HISTORY"."TIME_REPORT" IS '적립/사용일자';

COMMENT ON COLUMN "POINT_HISTORY"."POINT" IS '적립/사용포인트';

COMMENT ON COLUMN "POINT_HISTORY"."POINT_PLACE_NO" IS '적립/사용처번호';


CREATE TABLE "COMM_CATE" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(12)		NULL
);


CREATE TABLE "COMM_LIKE" (
	"COMMUNITY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMM_LIKE"."COMMUNITY_NO" IS '글번호';

COMMENT ON COLUMN "COMM_LIKE"."MEMBER_NO" IS '회원번호';


CREATE TABLE "ORDER_DETAIL" (
	"NO"	NUMBER		NOT NULL,
	"YESSMALL_PROD"	NUMBER		NOT NULL,
	"ORDER_NO"	NUMBER		NOT NULL,
	"CNT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ORDER_DETAIL"."NO" IS '내역번호';

COMMENT ON COLUMN "ORDER_DETAIL"."ORDER_NO" IS '주문번호';

COMMENT ON COLUMN "ORDER_DETAIL"."CNT" IS '수량';


CREATE TABLE "ZZIM" (
	"MARKET_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ZZIM"."MARKET_NO" IS '글번호';

COMMENT ON COLUMN "ZZIM"."MEMBER_NO" IS '회원번호';


CREATE TABLE "YESS_LIKED" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PROD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "YESS_LIKED"."MEMBER_NO" IS '회원번호';


CREATE TABLE "POINT_PLACE" (
	"NO"	NUMBER		NOT NULL,
	"PLACE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "POINT_PLACE"."NO" IS '적립/사용처번호';

COMMENT ON COLUMN "POINT_PLACE"."PLACE" IS '적립/사용처';


CREATE TABLE "NEWS_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"TYPE"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "NEWS_TYPE"."NO" IS '카테고리 번호';

COMMENT ON COLUMN "NEWS_TYPE"."TYPE" IS '공지사항 카테고리';


CREATE TABLE "QNA_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"QNA_TYPE"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "QNA_TYPE"."NO" IS '카테고리 번호';

COMMENT ON COLUMN "QNA_TYPE"."QNA_TYPE" IS '문의유형';


CREATE TABLE "REPORT_BOARD_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"TYPE"	VARCHAR2(20)		NOT NULL
);


CREATE TABLE "MARKET_ATTACHMENT" (
	"NO"	NUMBER		NOT NULL,
	"MARKET_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN('N','Y'))	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'O' CHECK(STATUS IN ('O', 'X'))	NOT NULL
);

COMMENT ON COLUMN "MARKET_ATTACHMENT"."MARKET_NO" IS '글번호';

COMMENT ON COLUMN "MARKET_ATTACHMENT"."ORIGIN_NAME" IS '기존 이름';

COMMENT ON COLUMN "MARKET_ATTACHMENT"."CHANGE_NAME" IS '변경된 이름';

COMMENT ON COLUMN "MARKET_ATTACHMENT"."FILE_PATH" IS '파일경로';

COMMENT ON COLUMN "MARKET_ATTACHMENT"."ENROLL_DATE" IS '등록일시';

COMMENT ON COLUMN "MARKET_ATTACHMENT"."THUMB_YN" IS '썸네일 여부';

COMMENT ON COLUMN "MARKET_ATTACHMENT"."STATUS" IS '상태';


CREATE TABLE "YESSMALL_REVIEW_ATTACHMENT" (
	"RV_FILE_NO"	NUMBER		NOT NULL,
	"RV_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN('N','Y'))	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'O' CHECK(STATUS IN ('O', 'X'))	NOT NULL
);

COMMENT ON COLUMN "YESSMALL_REVIEW_ATTACHMENT"."ORIGIN_NAME" IS '기존이름';

COMMENT ON COLUMN "YESSMALL_REVIEW_ATTACHMENT"."CHANGE_NAME" IS '변경된 이름';

COMMENT ON COLUMN "YESSMALL_REVIEW_ATTACHMENT"."FILE_PATH" IS '파일 경로';

COMMENT ON COLUMN "YESSMALL_REVIEW_ATTACHMENT"."ENROLL_DATE" IS '등록 일시';

COMMENT ON COLUMN "YESSMALL_REVIEW_ATTACHMENT"."THUMB_YN" IS '썸네일 여부';

COMMENT ON COLUMN "YESSMALL_REVIEW_ATTACHMENT"."STATUS" IS '상태';


CREATE TABLE "RECYCLE_ATTACHMENT" (
	"NO"	NUMBER		NOT NULL,
	"RECYCLE_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN('N', 'Y'))	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'O' CHECK(STATUS IN ('O', 'X'))	NOT NULL
);

COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."NO" IS '사진 번호';

COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."RECYCLE_NO" IS '분리수거번호';

COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."ORIGIN_NAME" IS '기존파일명';

COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."CHANGE_NAME" IS '바뀐파일명';

COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."FILE_PATH" IS '파일경로';

COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."ENROLL_DATE" IS '업로드일시';

COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."THUMB_YN" IS '썸네일여부';

COMMENT ON COLUMN "RECYCLE_ATTACHMENT"."STATUS" IS '상태';


CREATE TABLE "COMM_CMT" (
	"NO"	NUMBER		NOT NULL,
	"COMMUNITY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"CMT"	VARCHAR2(300)		NOT NULL,
	"CMT_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "COMM_CMT"."NO" IS '자유게시판 댓글 번호';

COMMENT ON COLUMN "COMM_CMT"."COMMUNITY_NO" IS '글번호';

COMMENT ON COLUMN "COMM_CMT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "COMM_CMT"."CMT" IS '댓글 내용';

COMMENT ON COLUMN "COMM_CMT"."CMT_DATE" IS '작성 날짜';

COMMENT ON COLUMN "COMM_CMT"."DELETE_YN" IS '삭제 여부';

COMMENT ON COLUMN "COMM_CMT"."MODIFY_DATE" IS '최종 수정 일시';


CREATE TABLE "COMM_HASHTAG" (
	"NO"	NUMBER		NOT NULL,
	"HASHTAG_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMM_HASHTAG"."NO" IS '글번호';


CREATE TABLE "HASHTAG" (
	"HASHTAG_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(255)		NOT NULL
);

COMMIT;

--------------------------------------------------------------------------
--FOREIGN KEY-------------------------------------------------------------
--------------------------------------------------------------------------

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"NO"
);

ALTER TABLE "COMM" ADD CONSTRAINT "PK_COMM" PRIMARY KEY (
	"NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "NEWS" ADD CONSTRAINT "PK_NEWS" PRIMARY KEY (
	"NO"
);

ALTER TABLE "REPORT_TYPE" ADD CONSTRAINT "PK_REPORT_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"NO"
);

ALTER TABLE "RECYCLE" ADD CONSTRAINT "PK_RECYCLE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "GRADE" ADD CONSTRAINT "PK_GRADE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY (
	"NO",
	"QNA_TYPE_NO"
);

ALTER TABLE "YESSMALL_PROD" ADD CONSTRAINT "PK_YESSMALL_PROD" PRIMARY KEY (
	"PROD_NO"
);

ALTER TABLE "YESSMALL_REVIEW" ADD CONSTRAINT "PK_YESSMALL_REVIEW" PRIMARY KEY (
	"RV_NO"
);

ALTER TABLE "YESSMALL_CATEGORY" ADD CONSTRAINT "PK_YESSMALL_CATEGORY" PRIMARY KEY (
	"PROD_CATE_NO"
);

ALTER TABLE "YESSMALL_ATTACHMENT" ADD CONSTRAINT "PK_YESSMALL_ATTACHMENT" PRIMARY KEY (
	"PROD_IMG_NO"
);

ALTER TABLE "MARKET" ADD CONSTRAINT "PK_MARKET" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MARKET_CMT" ADD CONSTRAINT "PK_MARKET_CMT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MARKET_TYPE" ADD CONSTRAINT "PK_MARKET_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "RECYCLE_TYPE" ADD CONSTRAINT "PK_RECYCLE_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "COMM_ATTACHMENT" ADD CONSTRAINT "PK_COMM_ATTACHMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "POINT_HISTORY" ADD CONSTRAINT "PK_POINT_HISTORY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "COMM_CATE" ADD CONSTRAINT "PK_COMM_CATE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "ORDER_DETAIL" ADD CONSTRAINT "PK_ORDER_DETAIL" PRIMARY KEY (
	"NO"
);

ALTER TABLE "POINT_PLACE" ADD CONSTRAINT "PK_POINT_PLACE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "NEWS_TYPE" ADD CONSTRAINT "PK_NEWS_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "QNA_TYPE" ADD CONSTRAINT "PK_QNA_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "REPORT_BOARD_TYPE" ADD CONSTRAINT "PK_REPORT_BOARD_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MARKET_ATTACHMENT" ADD CONSTRAINT "PK_MARKET_ATTACHMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "YESSMALL_REVIEW_ATTACHMENT" ADD CONSTRAINT "PK_YESSMALL_REVIEW_ATTACHMENT" PRIMARY KEY (
	"RV_FILE_NO"
);

ALTER TABLE "RECYCLE_ATTACHMENT" ADD CONSTRAINT "PK_RECYCLE_ATTACHMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "COMM_CMT" ADD CONSTRAINT "PK_COMM_CMT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "HASHTAG" ADD CONSTRAINT "PK_HASHTAG" PRIMARY KEY (
	"HASHTAG_NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "FK_QNA_TYPE_TO_FAQ_1" FOREIGN KEY (
	"QNA_TYPE_NO"
)
REFERENCES "QNA_TYPE" (
	"NO"
);

COMMIT;

--------------------------------------------------------------------------
--INSERT 구문--------------------------------------------------------------
--------------------------------------------------------------------------
INSERT INTO COMM VALUES(SEQ_COMM_NO.NEXTVAL, 1, 1, '분리수거 정보 공유합니다~', '좋아요 많이 눌러주시면 다음 편에 쓰겠습니다^_~', SYSDATE, 'N', SYSDATE, '100', 'N', 20 ,'해시태그');